[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]

# For foundry-devops lib
ffi = true

# Read access to ./images folder ( used for vm.readFile cheatcode )
fs_permissions = [{ access = "read", path = "./images" }]
